# Generated by Django 4.1.2 on 2022-10-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date_addeb',
            new_name='date_added',
        ),
    ]
